CREATE TABLE PDCA_VAN   (NUM_PROJETO        INT NOT NULL,
                         NOM_PROJETO        CHAR(70) NOT NULL, --VOU USAR COMO OBJECTIVO--
						 USUARIO_RESP       CHAR(08) NOT NULL,
						 AREA               CHAR(50) NOT NULL,
						 DAT_INCLUSAO       DATE NOT NULL,
						 DAT_REVISAO        DATE,
                         SEQ_ITEM     	    INT NOT NULL,
						 FOCO_OQUE          CHAR(100) NOT NULL,
						 MOTIVO_POR_QUE     CHAR(100) NOT NULL,
						 RESP_QUEM   	    CHAR(08) NOT NULL,
						 PRAZO_QUANDO       DATE NOT NULL,
						 LOCAL_ONDE         CHAR(50) NOT NULL,
						 ACOES_COMO         CHAR(500)NOT NULL,
						 VALORES_QUANTO     DECIMAL(16,5),
						 GANHOS_ESTIMADO    CHAR(100),
						 AVALIACAO25        CHAR(10),
						 AVALIACAO50        CHAR(10),
						 AVALIACAO75        CHAR(10),
						 AVALIACAO100       CHAR(10),
						 ANEXO       	    CHAR(500),
						 PRIMARY KEY(NUM_PROJETO, SEQ_ITEM))
